/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rubricbaseevaluation;

import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahtisham Ul Haq
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    boolean is_Correct = false;
    ArrayList<String> emailList = new ArrayList<>();
    ArrayList<String> passwordList = new ArrayList<>();

    public LoginFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        jLabel3.setText("");
        jLabel5.setText("");
        jLabel6.setText("");
        course_ID_combo_box.setVisible(false);
        emailList.add("samyanwahala@gmail.com");
        passwordList.add("samyan1234");
        emailList.add("hinasamr@gmail.com");
        passwordList.add("hina1234");
        emailList.add("rubina@uet.edu.pk");
        passwordList.add("rubina1234");
        emailList.add("yasir@uet.edu.pk");
        passwordList.add("samyan1234");
        emailList.add("rajamuzammil93@gmail.com");
        passwordList.add("muzammil1234");
        emailList.add("sohail.rashid@uet.edu.pk");
        passwordList.add("sohail1234");
        emailList.add("kashifali@uet.edu.pk");
        passwordList.add("kashif1234");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        closeBtn = new javax.swing.JButton();
        minimizeBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        email_InputField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        password_Field = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        show_pass_chk_box = new javax.swing.JCheckBox();
        LoginBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        course_ID_combo_box = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBounds(new java.awt.Rectangle(10, 10, 0, 0));
        setUndecorated(true);
        setType(java.awt.Window.Type.UTILITY);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        closeBtn.setBackground(new java.awt.Color(255, 0, 0));
        closeBtn.setText("X");
        closeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });

        minimizeBtn.setText("-");
        minimizeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
        });
        minimizeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        jLabel1.setText("LOGIN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimizeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeBtn)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeBtn)
                    .addComponent(minimizeBtn)
                    .addComponent(jLabel1))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel2.setText("Email");

        jLabel3.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel4.setText("Password");

        password_Field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                password_FieldMouseClicked(evt);
            }
        });

        jLabel5.setText("jLabel5");

        show_pass_chk_box.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        show_pass_chk_box.setText("Show Password");
        show_pass_chk_box.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show_pass_chk_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_pass_chk_boxActionPerformed(evt);
            }
        });

        LoginBtn.setBackground(new java.awt.Color(204, 255, 255));
        LoginBtn.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        LoginBtn.setText("Login");
        LoginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel6.setText("jlabel6");

        course_ID_combo_box.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 350, Short.MAX_VALUE)
                .addComponent(LoginBtn)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(show_pass_chk_box)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_Field, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(email_InputField, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(course_ID_combo_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_InputField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(show_pass_chk_box)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(course_ID_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(LoginBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void show_pass_chk_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_pass_chk_boxActionPerformed
        // TODO add your handling code here:
        if (show_pass_chk_box.isSelected()) {
            password_Field.setEchoChar((char) 0);
        } else {
            password_Field.setEchoChar('*');
        }
    }//GEN-LAST:event_show_pass_chk_boxActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:

        for (int i = 0; i < passwordList.size(); i++) {
            if (password_Field.getPassword().equals(passwordList.get(i))) {
                is_Correct = true;
                break;

            }
        }
        if (is_Correct) {
            jLabel5.setText("");
            String selected_ID = course_ID_combo_box.getSelectedItem().toString();
            if (selected_ID.equals("CS-162")) {
                Teacher.getInstance().setCourse_ID(selected_ID);
                Teacher.getInstance().setCourse_Title("Object Oriented Programming");
            } else {
                Teacher.getInstance().setCourse_ID(selected_ID);
                Teacher.getInstance().setCourse_Title("Object Oriented Programming ");
            }

            this.hide();
            ManageCLOs clos = new ManageCLOs();
            clos.setVisible(true);

        } else {

            jLabel5.setText("Invalid Password");
            password_Field.setText("");
        }


    }//GEN-LAST:event_LoginBtnActionPerformed

    private void password_FieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_password_FieldMouseClicked
        // TODO add your handling code here:
        for (int i = 0; i < emailList.size(); i++) {
            if (email_InputField.getText().equals(emailList.get(i))) {
                is_Correct = true;
                break;

            }
        }
        if (is_Correct) {
            jLabel3.setText("");

        } else {

            jLabel3.setText("Invalid Email");
            email_InputField.setText("");
        }
        if (email_InputField.getText().equals("samyanwahala@gmail.com")) {
            Teacher.getInstance().setTeacher_name("Samyan Wahala");
            jLabel6.setText("Course ID");

            course_ID_combo_box.addItem("CS-162");
            course_ID_combo_box.addItem("CS-162L");
            course_ID_combo_box.setVisible(true);

        } else if (email_InputField.getText().equals("hinasamr@gmail.com")) {
            Teacher.getInstance().setTeacher_name("Hina Samar");
            Teacher.getInstance().setCourse_ID("HU-111L");
            Teacher.getInstance().setCourse_Title("Communication Skills");

        } else if (email_InputField.getText().equals("rubina@uet.edu.pk")) {
            Teacher.getInstance().setTeacher_name("Rubina Siddique");
            Teacher.getInstance().setCourse_ID("MA-224");
            Teacher.getInstance().setCourse_Title("Multivariate Calculus");

        } else if (email_InputField.getText().equals("yasir@uet.edu.pk")) {

            Teacher.getInstance().setTeacher_name("Yasir Saleem");
            Teacher.getInstance().setCourse_ID("CMPE-222");
            Teacher.getInstance().setCourse_Title("Digital Logic Design");
        } else if (email_InputField.getText().equals("rajamuzammil93@gmail.com")) {

            Teacher.getInstance().setTeacher_name("Raja Muzammil Munir");
            Teacher.getInstance().setCourse_ID("CMPE-222L");
            Teacher.getInstance().setCourse_Title("Digital Logic Design");
        } else if (email_InputField.getText().equals("sohail.rashid@uet.edu.pk")) {

            Teacher.getInstance().setTeacher_name("Sohail Rashid");
            Teacher.getInstance().setCourse_ID("QT-101");
            Teacher.getInstance().setCourse_Title("ranslation of the Holy Quran - I");
        } else if (email_InputField.getText().equals("kashifali@uet.edu.pk")) {

            Teacher.getInstance().setTeacher_name("Dr Kashif Ali Khan");
            Teacher.getInstance().setCourse_ID("MA-343");
            Teacher.getInstance().setCourse_Title("Applied Probability and Statistics");
        }
    }//GEN-LAST:event_password_FieldMouseClicked

    private void minimizeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeBtnActionPerformed
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JComboBox<String> course_ID_combo_box;
    private javax.swing.JTextField email_InputField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton minimizeBtn;
    private javax.swing.JPasswordField password_Field;
    private javax.swing.JCheckBox show_pass_chk_box;
    // End of variables declaration//GEN-END:variables
}
