/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rubricbaseevaluation;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ahtisham Ul Haq
 */
public class MarksEvaluation extends javax.swing.JFrame {

    /**
     * Creates new form MarksEvaluation
     */
    DefaultTableModel model, model2;
    private int selectedRowIndex;
    private int selectedColIndex;
    Students s;
    Assesments ass;

    public MarksEvaluation() {
        initComponents();
        this.setLocationRelativeTo(null);
        s = new Students();

        regNoLabel.setText("");
        std_nameLabel.setText("");
        model = new DefaultTableModel();
        model2 = new DefaultTableModel();

        model.addColumn("Name");
        model.addColumn("Registration");
        model.addColumn("Gender");
        studentSearchTable.setModel(model);
        model2.addColumn("Rubric");
        model2.addColumn("Component Marks");
        model2.addColumn("Obtain Comp_Marks");
        searchAssesmentTable.setModel(model2);
        marksEvaluationPanel.setVisible(false);
        searchTablePanel.setVisible(false);
        ass = new Assesments();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        studentSearchField = new javax.swing.JTextField();
        StudentSearchBtn = new javax.swing.JButton();
        marksEvaluationPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        regNoLabel = new javax.swing.JLabel();
        std_nameLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchAssesmentTable = new javax.swing.JTable();
        add_componentBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        searchAssesmentField = new javax.swing.JTextField();
        searchAssesmentBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        closLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        searchTablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentSearchTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel1.setText("Marks Evaluation");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("X");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("-");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jButton1)
                .addComponent(jButton2))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Student", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 11))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        jLabel2.setText("Registration No");

        StudentSearchBtn.setBackground(new java.awt.Color(255, 255, 255));
        StudentSearchBtn.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        StudentSearchBtn.setText("Search");
        StudentSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentSearchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StudentSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(studentSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(studentSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StudentSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        marksEvaluationPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Registration No     :");

        jLabel4.setText("Name                     :");

        regNoLabel.setText("jLabel7");

        std_nameLabel.setText("jLabel8");

        searchAssesmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        searchAssesmentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchAssesmentTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(searchAssesmentTable);

        add_componentBtn.setText("Add");
        add_componentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_componentBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Search Assessment :");

        searchAssesmentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAssesmentFieldActionPerformed(evt);
            }
        });

        searchAssesmentBtn.setText("search");
        searchAssesmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAssesmentBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("CLO                       :");

        closLabel.setText("jLabel9");

        jLabel10.setBackground(new java.awt.Color(204, 204, 255));
        jLabel10.setText("Click on row and press Add button to enter component marks");

        javax.swing.GroupLayout marksEvaluationPanelLayout = new javax.swing.GroupLayout(marksEvaluationPanel);
        marksEvaluationPanel.setLayout(marksEvaluationPanelLayout);
        marksEvaluationPanelLayout.setHorizontalGroup(
            marksEvaluationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marksEvaluationPanelLayout.createSequentialGroup()
                .addGroup(marksEvaluationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, marksEvaluationPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(marksEvaluationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(add_componentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, marksEvaluationPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(marksEvaluationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(marksEvaluationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(marksEvaluationPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(searchAssesmentField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(searchAssesmentBtn))
                                .addGroup(marksEvaluationPanelLayout.createSequentialGroup()
                                    .addGroup(marksEvaluationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(marksEvaluationPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(closLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(marksEvaluationPanelLayout.createSequentialGroup()
                                            .addGroup(marksEvaluationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4))
                                            .addGap(14, 14, 14)
                                            .addGroup(marksEvaluationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(regNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(std_nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        marksEvaluationPanelLayout.setVerticalGroup(
            marksEvaluationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marksEvaluationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(marksEvaluationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(regNoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(marksEvaluationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(std_nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(marksEvaluationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(closLabel))
                .addGap(23, 23, 23)
                .addGroup(marksEvaluationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(marksEvaluationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchAssesmentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchAssesmentBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(add_componentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        studentSearchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        studentSearchTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentSearchTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studentSearchTable);

        javax.swing.GroupLayout searchTablePanelLayout = new javax.swing.GroupLayout(searchTablePanel);
        searchTablePanel.setLayout(searchTablePanelLayout);
        searchTablePanelLayout.setHorizontalGroup(
            searchTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        searchTablePanelLayout.setVerticalGroup(
            searchTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTablePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(marksEvaluationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(marksEvaluationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(null, "Do you want To Exit the program", "Confirm", 0, 1);
        if (i == 0) {
            System.exit(0);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void StudentSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentSearchBtnActionPerformed
        // TODO add your handling code here:
        String regNo = studentSearchField.getText();

        if (!regNo.equals("")) {
            studentSearchField.setText("");
            searchTablePanel.setVisible(true);
            marksEvaluationPanel.setVisible(false);
            s = Teacher.getInstance().seearchStudent(regNo);
            selectedRowIndex = studentSearchTable.getSelectedRow();
            if (s != null) {

                addRowData(s);
            }

        }


    }//GEN-LAST:event_StudentSearchBtnActionPerformed

    private void studentSearchTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentSearchTableMouseClicked
        // TODO add your handling code here:

        for (int i = 0; i < model2.getRowCount(); i++) {
            model2.removeRow(i);
        }
        marksEvaluationPanel.setVisible(true);
        searchTablePanel.setEnabled(false);
        regNoLabel.setText(s.getRegisterationNO());
        std_nameLabel.setText(s.getStudent_name());
        closLabel.setText(Teacher.getInstance().getAssessmentList().get(0).getClos());
        searchAssesmentField.setText("");

    }//GEN-LAST:event_studentSearchTableMouseClicked

    private void searchAssesmentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchAssesmentTableMouseClicked
        // TODO add your handling code here:
        /*selectedColIndex = jTable2.getSelectedColumn();*/
        selectedRowIndex = searchAssesmentTable.getSelectedRow();

    }//GEN-LAST:event_searchAssesmentTableMouseClicked

    private void add_componentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_componentBtnActionPerformed
        // TODO add your handling code here:

        ArrayList<Double> obt_marks = new ArrayList<>();
        int count = model2.getRowCount();
        Object newRows[] = new Object[count];
        for (int i = 0; i < count; i++) {
            newRows[i] = searchAssesmentTable.getValueAt(i, 2);

        }
        for (int i = 0; i < count; i++) {
            if (newRows[i] != "") {
                if (Integer.parseInt(newRows[i].toString()) <= ass.getComponent_marks().get(i)) {
                    try {
                        obt_marks.add(Double.parseDouble(newRows[i].toString()));
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, "Invalid Field");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid Field");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Empty Field");
            }
        }
        String d = JOptionPane.showInputDialog(null, "Enter Max Level");
        if (d != "") {
            double max_level = 0.0;
            try {

                max_level = Double.parseDouble(d);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Empty", "Alert", 0);
            }
            ArrayList<Double> list = new ArrayList<>();
            list = getStudentMarks(obt_marks, ass, max_level);
            double sum = 0.0;
            for (int i = 0; i < list.size(); i++) {
                sum = sum + list.get(i);
            }
            s.setObtain_marks(sum);
            ObtainedMarks obtain_marks = new ObtainedMarks();
            obtain_marks.jLabel3.setText(s.getStudent_name());
            obtain_marks.jLabel5.setText(s.getRegisterationNO());
            obtain_marks.jLabel7.setText("" + s.getObtain_marks().get(0));
            obtain_marks.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Empty", "Alert", 0);
        }
    }//GEN-LAST:event_add_componentBtnActionPerformed
    private ArrayList<Double> getStudentMarks(ArrayList<Double> ob_marks, Assesments as, double max_level) {
        ArrayList<Double> marks = new ArrayList<>();
        for (int i = 0; i < ob_marks.size(); i++) {
            double result = ob_marks.get(i) * as.getComponent_marks().get(i);
            result = result / max_level;
            marks.add(result);
        }

        return marks;
    }
    private void searchAssesmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAssesmentBtnActionPerformed
        // TODO add your handling code here:
        String assesment = searchAssesmentField.getText();
        if (!assesment.equals("")) {

            ass = Teacher.getInstance().searchAssesment(assesment);
            if (ass != null) {
                for (int i = 0; i < model2.getRowCount(); i++) {
                    model2.removeRow(i);
                }
                Object rowData[] = new Object[3];
                int size = ass.getRubrics().size();
                for (int i = 0; i < size; i++) {
                    rowData[0] = ass.getRubrics().get(i);
                    rowData[1] = ass.getComponent_marks().get(i);
                    rowData[2] = "";
                    model2.addRow(rowData);
                }

            }
        }
    }//GEN-LAST:event_searchAssesmentBtnActionPerformed

    private void searchAssesmentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAssesmentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchAssesmentFieldActionPerformed
    private Students getRowData(int index) {
        Students std = new Students();
        if (index != -1) {

            Object regNO = model.getValueAt(index, 1);
            std = Teacher.getInstance().seearchStudent(regNO.toString());
        }
        return std;
    }

    private void addRowData(Students s) {
        Object rowData[] = new Object[3];
        for (int i = 0; i < model.getRowCount(); i++) {
            model.removeRow(i);
        }
        if (!s.getStudent_name().equals("")) {
            rowData[0] = s.getStudent_name();
            rowData[1] = s.getRegisterationNO();
            rowData[2] = s.getGender();
            model.addRow(rowData);

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarksEvaluation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarksEvaluation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarksEvaluation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarksEvaluation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarksEvaluation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton StudentSearchBtn;
    private javax.swing.JButton add_componentBtn;
    private javax.swing.JLabel closLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel marksEvaluationPanel;
    private javax.swing.JLabel regNoLabel;
    private javax.swing.JButton searchAssesmentBtn;
    private javax.swing.JTextField searchAssesmentField;
    private javax.swing.JTable searchAssesmentTable;
    private javax.swing.JPanel searchTablePanel;
    private javax.swing.JLabel std_nameLabel;
    private javax.swing.JTextField studentSearchField;
    private javax.swing.JTable studentSearchTable;
    // End of variables declaration//GEN-END:variables
}
